# -*- coding: utf-8 -*-
"""Traffic Accidents Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjkzcm5nX5qEimjOmQcVJmqAuR1pTyMg
"""

# ============================================================
# STEP 1: INSTALL REQUIRED LIBRARIES
# ============================================================

# Run this in terminal or command prompt
# pip install pandas matplotlib seaborn folium

# ============================================================
# STEP 2: IMPORT LIBRARIES
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import folium
from folium.plugins import HeatMap

# ============================================================
# STEP 3: LOAD DATASET
# ============================================================

df = pd.read_csv("/content/traffic_accident_data.csv")

# Display first 5 rows
print(df.head())

# ============================================================
# STEP 4: DATASET INFORMATION
# ============================================================

print("\nDataset Info:\n")
print(df.info())

print("\nMissing Values:\n")
print(df.isnull().sum())

print("\nStatistical Summary:\n")
print(df.describe())

# ============================================================
# STEP 5: ROAD CONDITION ANALYSIS
# ============================================================

print("\nRoad Condition Counts:\n")
print(df['Road_Condition'].value_counts())

plt.figure(figsize=(10,6))

sns.countplot(x='Road_Condition', data=df)

plt.title('Accidents by Road Condition')
plt.xlabel('Road Condition')
plt.ylabel('Number of Accidents')

plt.show()

# ============================================================
# STEP 6: WEATHER CONDITION ANALYSIS
# ============================================================

print("\nWeather Condition Counts:\n")
print(df['Weather_Condition'].value_counts())

plt.figure(figsize=(10,6))

sns.countplot(x='Weather_Condition', data=df)

plt.title('Accidents by Weather Condition')
plt.xlabel('Weather Condition')
plt.ylabel('Number of Accidents')

plt.show()

# ============================================================
# STEP 7: TIME OF DAY ANALYSIS
# ============================================================

print("\nTime of Day Counts:\n")
print(df['Time_of_Day'].value_counts())

plt.figure(figsize=(10,6))

sns.countplot(x='Time_of_Day', data=df)

plt.title('Accidents by Time of Day')
plt.xlabel('Time of Day')
plt.ylabel('Number of Accidents')

plt.show()

# ============================================================
# STEP 8: ACCIDENT SEVERITY ANALYSIS
# ============================================================

print("\nSeverity Counts:\n")
print(df['Severity'].value_counts())

plt.figure(figsize=(8,5))

sns.countplot(x='Severity', data=df)

plt.title('Accident Severity Distribution')
plt.xlabel('Severity')
plt.ylabel('Count')

plt.show()

# ============================================================
# STEP 9: VEHICLE TYPE ANALYSIS
# ============================================================

print("\nVehicle Type Counts:\n")
print(df['Vehicle_Type'].value_counts())

plt.figure(figsize=(10,6))

sns.countplot(x='Vehicle_Type', data=df)

plt.title('Accidents by Vehicle Type')
plt.xlabel('Vehicle Type')
plt.ylabel('Count')

plt.show()

# ============================================================
# STEP 10: ACCIDENT HOTSPOT ANALYSIS
# ============================================================

print("\nHotspot Counts:\n")
print(df['Location'].value_counts())

plt.figure(figsize=(12,6))

sns.countplot(x='Location', data=df)

plt.title('Accident Hotspots')
plt.xlabel('Location')
plt.ylabel('Number of Accidents')

plt.xticks(rotation=15)

plt.show()

# ============================================================
# STEP 11: ACCIDENTS BY HOUR
# ============================================================

plt.figure(figsize=(12,6))

sns.histplot(df['Hour'], bins=24, kde=True)

plt.title('Accidents by Hour')
plt.xlabel('Hour')
plt.ylabel('Accident Count')

plt.show()

# ============================================================
# STEP 12: WEATHER VS SEVERITY ANALYSIS
# ============================================================

plt.figure(figsize=(12,6))

sns.countplot(x='Weather_Condition',
              hue='Severity',
              data=df)

plt.title('Weather Condition vs Severity')
plt.xlabel('Weather Condition')
plt.ylabel('Count')

plt.show()

# ============================================================
# STEP 13: ROAD CONDITION VS SEVERITY
# ============================================================

plt.figure(figsize=(12,6))

sns.countplot(x='Road_Condition',
              hue='Severity',
              data=df)

plt.title('Road Condition vs Severity')
plt.xlabel('Road Condition')
plt.ylabel('Count')

plt.show()

# ============================================================
# STEP 14: CORRELATION HEATMAP
# ============================================================

# Convert categorical columns into numerical values

encoded_df = df.copy()

encoded_df['Road_Condition'] = encoded_df['Road_Condition'].astype('category').cat.codes
encoded_df['Weather_Condition'] = encoded_df['Weather_Condition'].astype('category').cat.codes
encoded_df['Severity'] = encoded_df['Severity'].astype('category').cat.codes
encoded_df['Time_of_Day'] = encoded_df['Time_of_Day'].astype('category').cat.codes
encoded_df['Vehicle_Type'] = encoded_df['Vehicle_Type'].astype('category').cat.codes
encoded_df['Location'] = encoded_df['Location'].astype('category').cat.codes

# Correlation matrix

corr = encoded_df.corr(numeric_only=True)

plt.figure(figsize=(12,8))

sns.heatmap(corr,
            annot=True,
            cmap='coolwarm')

plt.title('Correlation Heatmap')

plt.show()

# ============================================================
# STEP 15: CREATE ACCIDENT HOTSPOT MAP
# ============================================================

# Create map center

map_center = [df['Latitude'].mean(),
              df['Longitude'].mean()]

# Create folium map

accident_map = folium.Map(location=map_center,
                          zoom_start=12)

# Create heatmap data

heat_data = [[row['Latitude'],
              row['Longitude']]
             for index, row in df.iterrows()]

# Add heatmap

HeatMap(heat_data).add_to(accident_map)

# Save map

accident_map.save("accident_hotspot_map.html")

print("\nHotspot map created successfully!")

# ============================================================
# STEP 16: SAVE CLEANED DATASET
# ============================================================

df.to_csv("cleaned_traffic_accident_data.csv",
          index=False)

print("\nCleaned dataset saved successfully!")

